
services:
  pokedexapp:
    #si la bd no se levanta, pokedexapp no se levanta
    depends_on:
      - db
    build: 
      # Si el Dockerfile estuviera en otra carpeta, sería la direccion en donde este el dockerfile por ejemplo ./src
      context: .
      #en caso de llamar otro dockerfile se pone alli
      dockerfile: Dockerfile
    image: pokedex-docker
    container_name: pokedexapp
    restart: always # reiniciar el contenedor si se detiene
    ports:
      - "${PORT}:${PORT}"
    # working_dir: /var/www/pokedex
    environment:
      MONGODB: ${MONGODB}
      PORT: ${PORT}
      DEFAULT_LIMIT: ${DEFAULT_LIMIT}
    volumes:
      - ./public:/usr/src/app/public 

  db:
    image: mongo:5
    container_name: mongo-poke
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: nest-pokemon
    volumes: # Esto se mantiene la data de la base de datos
      - ./mongo:/data/db